version: "3.8"

services:    
  db:
    env_file:
      - .env
    build: ./mariadb/.
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - DataBase:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u$$MY_USER", "-p$$MY_PASS"]
      interval: 10s
      timeout: 5s
      retries: 3


  wordpress:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build: ./wordpress/.
    container_name: wordpress-cont
    image: wordpress:mytag
    restart: always
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build: ./nginx/.
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "80:80"
    restart: always
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - app-network

volumes:
  Wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/files
  DataBase:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/db
  
networks:
  app-network:
    name: web-network
